version: "3.9"

services:
  db:
    container_name: shiftplan_postgres
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "shiftplandb"
      POSTGRES_USER: "shiftplan"
      POSTGRES_PASSWORD: "dev_password"
    volumes:
      - shiftplan-data:/var/lib/postgresql/data/

volumes:
  shiftplan-data:
